### PR TITLE
added textfield widget's sample

### PR DESCRIPTION
**Pull request by samyakjain26**

### CODE REVIEW

**Comment by samyakjain26** [comment]
Screenshot_20211004-124205
)

**Comment by samyakjain26** [comment]
Screenshot_20211004-124205

**Comment by AryanKhubchandani** [comment]
Hey @samyakjain26! Sorry but I have already assigned this issue to someone else. 
The general procedure is to ask for assignment of the issue first and once you are assigned the issue, then you can create a PR.
Make sure to get assigned to the issue first before working on it next time. 
Incase the person assigned to this issue is not able to complete the task, I will consider this PR. 
Hope you understand, thankyou!

**Comment by AryanKhubchandani** [comment]
The issue has been solved by other user. You can check out other issues and get assigned to them. 
Thankyou!

**Comment by samyakjain26** [comment]
Hello @AryanKhubchandani can you please assign me another widget so that i can work on it

**Comment by AryanKhubchandani** [comment]
> Hello @AryanKhubchandani can you please assign me another widget so that i can work on it

Sure, there are three more issues related to widgets which are open right now. Just go to the issue you want to work on and leave a comment, I will assign it to you.

**Pull request closed without merging**
