### PR TITLE
card widget implemented

### PR DESCRIPTION
**Pull request by Nit89**
I implemented a card widget named as CardSample, I built different cards to show the various way of using cards:

- first card is a simple card 
- second card is rounded by using RoundedRectangleBorder 
- third card is a colored card 
- fourth card is made by  using a network image  and applied greyscale color filter
- fifth card is a colored card  wrapped with image and text 
- official documentation : [card class](https://api.flutter.dev/flutter/material/Card-class.html)

WhatsApp Image 2021-10-02 at 7 08 35 PM

WhatsApp Image 2021-10-02 at 7 08 38 PM

### CODE REVIEW

**Review by AryanKhubchandani — CHANGES_REQUESTED** [review]
Great work @Nit89 ! But there are a few changes required:
1) The title should be Card only
2) The backgroundColor and appBar color needs to be in accordance to the homepage

**Comment by Nit89** [comment]
> Great work @Nit89 ! But there are a few changes required:
> 
> 1. The title should be 'Card' only
> 2. The backgroundColor and appBar color needs to be in accordance to the homepage

**Comment by Nit89** [comment]
issues resolved  
- Title changed to Card
- background-color is changed 
Plz have a  look    #12

**Review by AryanKhubchandani — CHANGES_REQUESTED** [review]
The appBar color also needs to be changed from blue to the color used in other routes, as I mentioned before. 
Also there is a conflict which needs to be resolved in homepage, please look into that.
Thanks

**Comment by Nit89** [comment]
can you  tell me what color is used in app bar ?

**Pull request closed without merging**
