### PR TITLE
Added Cupertino-Widgets

### LINKED ISSUE #163: Add Cupertino-Widgets
Will add Beautiful and high-fidelity widgets for current iOS design language.
Going to add 10+ cupertino widgets 
Here are some : 
- CupertinoActionSheet : An iOS-style modal bottom action sheet to choose an option among many.
- CupertinoActivityIndicator : An iOS-style activity indicator. Displays a circular 'spinner'.
- CupertinoAlertDialog : An iOS-style alert dialog.
- CupertinoButton : An iOS-style button.
- CupertinoContextMenu : An iOS-style full-screen modal route that opens when the child is long-pressed. Used to display relevant actions for your content.
- CupertinoDatePicker : An iOS-style date or date and time picker.
- CupertinoDialogAction : A button typically used in a CupertinoAlertDialog.
- CupertinoPopupSurface : Rounded rectangle surface that looks like an iOS popup surface, such as an alert dialog or action sheet.
- CupertinoSearchTextField : An iOS-style search field.
- CupertinoSlidingSegmentedControl : An iOS-13-style segmented control. Used to select mutually exclusive options in a horizontal list.
- CupertinoSlider : Used to select from a range of values.
- CupertinoSwitch : An iOS-style switch. Used to toggle the on/off state of a single setting.
- CupertinoTimerPicker : An iOS-style countdown timer picker.
etc.

### PR DESCRIPTION
**Pull request by Shah-Aayush**
closes #163 
> - High-Fidelity widgets for current iOS design language implemented with working examples of each widget.
> - Build iOS app file and Tested on iOS devices
> - Here is the preview of some cupertino-widgets : 

https://user-images.githubusercontent.com/63921776/137256494-c21a0e94-48de-4e7a-be5c-aaad4304b09d.mp4

.

### CODE REVIEW

**Comment by AryanKhubchandani** [comment]
Hey @Shah-Aayush, are you working on this? You haven't responded to my message yet, so please update me

**Comment by Shah-Aayush** [comment]
Hi @AryanKhubchandani!
Thanks for reviewing my PR. I made this `Cupertino-widgets` section for the sole purpose of guiding new devs in flutter towards iOS-style design language. Often beginners in flutter devs like me tend to make their app's UI based on Material Design only, without explicitly thinking about Cupertino Design which apple uses. 
Here are my points : 
- The way you have implemented the widgets does not follow the guidelines. You cannot make a list tile as a category for Cupertino Widgets, you have to include different Cupertino widgets within the Widget List only
    > As all the implemented widgets in this Cupertino-widgets section are of pretty basic level and require no third-party package installation so implementing each of these small widgets in a different section would be a redundancy. I suggest that minor widgets should be included in one section together so a learner can easily navigate through different Cupertino widgets and can immediately spot the difference between native android style `Material Design` widgets and iOS-style `Cupertino` widgets.
- All the widgets are required to have different descriptions and different links to the official documentation
    > The [link](https://flutter.dev/docs/development/ui/widgets/cupertino) provided in the description section is of the official flutter docs only!   
       SnapShot of flutter Cupertino widgets doc
 As you can see here the flutter team has beautifully made all different sections for the different basic widgets on one page only. All detailed information about all the used widgets in this section can be easily found here as I followed the same order in the implementation part too.
- Colors should not be hardcode
    > Thanks for pointing this out! I know that this will lead to absurd UI when changing dark-light themes so I will look into this.
---

Sorry for the late response because my exams are going on but in few days I'll start contributing again
I am planning to improve this `Cupertino-widgets` section very soon in which I will do the following things :
- Split this section with smaller sections consisting of similar widgets
- Will add specific doc link respected to a specific widget
- No hardcoded color values!
So I am suggesting you merge this PR and I'll open another issue i.e. `Improving Cupertino-Widgets` in which I'll work on the things stated above.
Thanks and regards.

**Comment by AryanKhubchandani** [comment]
Alright, I understand your concern regarding the material and cupertino difference. I am willing to add a new feature to solve this issue. Two different tabs will be included in the home page, one for material widgets and one for cupertino widgets. Once you open Cupertino Widgets, we can implement a cupertino based UI. This will make the application more approachable for iOS users as well.
I will merge this PR for now, and after you are done with your exams, you can improve this in the Cupertino widgets tab which will have exclusive Cupertino Design. 
I will keep the tab ready by that time.
Thanks for the contribution and all the best for your exams!

**Comment by Shah-Aayush** [comment]
> I would like you to resolve conflicts and remove harcoded values before I can merge this PR as I cannot make an exception to the guidelines being followed. Alternatively, you can improve on this PR only once you are done with your exam as I can understand it will be difficult for you to give time during exams.

Thank you @AryanKhubchandani!
- I resolved merge conflicts now.
- I'll try to remove hardcoded values as soon as possible
So now I want you to create that Cupertino widgets section fully implemented with Cupertino widgets! That's a brilliant idea. I'll work on that as soon as my exams get completed :)

**Comment by Shah-Aayush** [comment]
@AryanKhubchandani I'm opening another PR for improving cupertino widgets in which I'll do the following : 
- Add more cupertino widgets
- Separate documentation for each widget
- No hardcoded values
- Improve UI for darkmode
> + Any other suggestions 

Please merge and close this PR and assign the `improve-cupertino-widgets` issue to me :)

**Comment by AryanKhubchandani** [comment]
> @AryanKhubchandani I'm opening another issue for improving cupertino widgets in which I'll do the following :
> 
> * Add more cupertino widgets
> * Separate documentation for each widget
> * No hardcoded values
> * Improve UI for darkmode
> 
> > + Any other suggestions
> 
> Please merge and close this PR and assign the `improve-cupertino-widgets` issue to me :)
> 
> Opened issue #219. Kindly assign this issue to me 🚀

Great, I will merge this PR for now.

**Pull request merged**
