### PR TITLE
Splash Screen for the app

### PR DESCRIPTION
**Pull request by iamsandipanbera**

### CODE REVIEW

**Comment by AryanKhubchandani** [comment]
Hey @iamsandipanbera! Please attach the screenshots of your work. 
Also make sure to get the issue assigned to you before creating a PR by commenting on the issue.
Thankyou

**Comment by iamsandipanbera** [comment]
Screenshot_2021-10-04-15-47-55-1

**Review by AryanKhubchandani — APPROVED** [review]
Looks good to me, great work @iamsandipanbera!

**Comment by iamsandipanbera** [comment]
Thanks @AryanKhubchandani

**Pull request merged**
