### PR TITLE
#24 Added description to widget catalogue

### PR DESCRIPTION
**Pull request by nirad17**

### CODE REVIEW

**Comment by AryanKhubchandani** [comment]
@nirad17 Please respond, otherwise I will have to close this PR.

**Comment by AryanKhubchandani** [comment]
> > @nirad17 Please respond, otherwise I will have to close this PR.
> 
> I'm getting this error whenever I'm trying to open app after fetch upstream. er

I guess your Flutter isn't updated. So use `flutter upgrade` to get the upgraded versions. 
Let me know if the problem persists after this.

**Comment by nirad17** [comment]
> @nirad17 Please attach screenshots of your work, otherwise I will have to close this PR. It has been almost a week, hope you understand.

I'm really sorry I had attached Screen shots in the issues #24

**Comment by nirad17** [comment]
> @nirad17 Please attach screenshots of your work, otherwise I will have to close this PR. It has been almost a week, hope you understand.

@AryanKhubchandani Please find the Screen shots below :
textField
button
card
column
dialogBox
dropDown
expanded
gridList
icon
image
opacity
reorderableListView
row
snackBar
stack
switch
table
text

**Pull request closed without merging**
