### PR TITLE
Added code tab

### PR DESCRIPTION
**Pull request by suryaa62**
showing screenshot\video will not be feasible.

### CODE REVIEW

**Comment by AryanKhubchandani** [comment]
Give me some time, I will test this out locally.

**Comment by AryanKhubchandani** [comment]
Please resolve the conflicts @suryaa62

**Comment by AryanKhubchandani** [comment]
Sorry, I forgot about that and merged one. I was going to fix that myself but looks like you already did that xD
I am currently checking out this PR on my machine. Will let you know once I am done reviewing.

**Comment by AryanKhubchandani** [comment]
Also, exactly what code have you used for each widget? Did you manually right it for every widget or copy it.

**Comment by suryaa62** [comment]
> Also, exactly what code have you used for each widget? Did you manually type it for every widget or copy it.

i copied it

**Pull request merged**
