### PR TITLE
Feature added : filter widget by category

### PR DESCRIPTION
**Pull request by suryaa62**
https://user-images.githubusercontent.com/72617587/136613622-976cd73d-e036-41d4-94e5-deece89ef2a7.mp4

#101

### CODE REVIEW

**Comment by AryanKhubchandani** [comment]
Alternatively, we can also consider to use a different widget for including filters, like a bottom sheet and just include a TextButton at the top.

**Comment by suryaa62** [comment]
https://user-images.githubusercontent.com/72617587/136654119-a2e5cc4f-a4c5-45b8-bc9c-5f8358cac3cb.mp4


is this fine?.. if yes then i will push the changes

**Comment by suryaa62** [comment]
similarly there is no way to change the padding...

**Comment by AryanKhubchandani** [comment]
Ahh alright, it's okay then
Please resolve the conflicts before I merge this PR though.

**Pull request merged**
