### PR TITLE
added pageview Widget

### PR DESCRIPTION
**Pull request by samyakjain26**

### CODE REVIEW

**Comment by samyakjain26** [comment]
https://user-images.githubusercontent.com/79244707/136182547-8385e9de-7503-4066-bc27-b6e768f858d1.mp4

**Comment by samyakjain26** [comment]
@AryanKhubchandani Please Find attached the screen recording

**Comment by samyakjain26** [comment]
I have Updated Please check @AryanKhubchandani

**Review by AryanKhubchandani — COMMENTED** [review]
Looks good to me, but please attach a screen recording of the implementation for the approval.

**Comment by samyakjain26** [comment]
https://user-images.githubusercontent.com/79244707/136228303-5976d2aa-0fb6-4199-823b-3d40d5c78469.mp4

**Review by AryanKhubchandani — APPROVED** [review]
GG @samyakjain26! The implementation is of pages, so it made more sense to use the word 'pages' instead of 'screens', so I updated it. The rest of the implementation is alright. 
Thanks for your contribution!

**Pull request merged**
