### PR TITLE
Add Settings Widget

### PR DESCRIPTION
**Pull request by cloudy3**
Add Settings Widget and followed the Contributing Guidelines for Hacktoberfest 2021.
Fixes Issue: #8

### CODE REVIEW

**Review by AryanKhubchandani — COMMENTED** [review]
I request you to attach screenshot of the same for review

**Comment by cloudy3** [comment]
image
image
Here you go!

**Review by AryanKhubchandani — COMMENTED** [review]
Good work @cloudy3 , but our requirement is actually different from what you implemented.

**Comment by cloudy3** [comment]
Oh how so?

**Review by AryanKhubchandani — CHANGES_REQUESTED** [review]
1) The setting menu needs to be added in the appBar as a drawer, not as a widget in the widget list
2) No features should be present in the menu for now, it should be empty
3) The backgroundColor should be in accordance to the rest of the application
Hope you understand and make changes
Thankyou

**Comment by cloudy3** [comment]
Sure I'll make the updates accordingly, just to make sure there aren't any miscommunication, could you maybe draw over my screenshot showcasing your requirements? By settings menu. do you mean an icon on the top left hand corner of the appBar etc? Which then navigates to a settings screen?

**Comment by AryanKhubchandani** [comment]
> Sure I'll make the updates accordingly, just to make sure there aren't any miscommunication, could you maybe draw over my screenshot showcasing your requirements? By settings menu. do you mean an icon on the top left hand corner of the appBar etc? Which then navigates to a settings screen?

I am sorry for not being able to communicate the issue properly before, you just need to add a Drawer in the Scaffold widget of `homepage.dart`, which will be used as a setting menu. Various features need to be implemented afterwards in the setting menu, for which a drawer needs to be initialized.
Also, make sure the background is in accordance to the UI of the application.

**Comment by AryanKhubchandani** [comment]
P.S. If you are willing, you can implement a customized Drawer using animation and create a different PR for that afterwards. You can use your creativity and use a dynamic UI for it.

**Comment by cloudy3** [comment]
I will close this PR and create a new one

**Comment by AryanKhubchandani** [comment]
> I will close this PR and create a new one
Sure

**Comment by AryanKhubchandani** [comment]
> I will close this PR and create a new one

Sure

**Pull request closed without merging**
