### PR TITLE
Added File Image under Image view

### PR DESCRIPTION
**Pull request by sidheshwar-s**
The page was not scrollable before, I have fixed it and also added Image.file() implementation using the file picker plugin.

**View before choosing an image:**

Screenshot_1633455986

**View after choosing an image:**

_The container will be replaced by the image_

Screenshot_1633455995

### CODE REVIEW

**Review by AryanKhubchandani — APPROVED** [review]
GG @sidheshwar-s,! An issue was about to be raised for the same, thanks for fixing it in advance :)

**Comment by sidheshwar-s** [comment]
yes, please make it valid for hacktoberfest

**Comment by sidheshwar-s** [comment]
> If you want to get this PR valid for hacktoberfest, let me know as I will have to raise an issue for that first. Thankyou!

Yup, please do make it valid for hacktoberfest

**Comment by AryanKhubchandani** [comment]
Hey @sidheshwar-s, please refer to issue #70 and make those additional changes.

**Comment by sidheshwar-s** [comment]
> Hey @sidheshwar-s, please refer to issue #70 and make those additional changes.

issue - #70 

Done with the changes, you can review it. 

Memory images will be generally used when dealing with flutter web, so I thought it would be a nice example to fetch an image from the internet, convert it into bytes and show that image. 

Screenshot_1633511543

Screenshot_1633511551

**Review by AryanKhubchandani — COMMENTED** [review]
Everything looks good to me, GG @sidheshwar-s!

**Pull request merged**
