### PR TITLE
ClipRRect Widget added

### PR DESCRIPTION
**Pull request by ShravanSeth**

### CODE REVIEW

**Comment by ShravanSeth** [comment]
[2021-10-17 23-08-50.zip](https://github.com/ACM-VIT/fludget/files/7360547/2021-10-17.23-08-50.zip)

**Comment by ShravanSeth** [comment]
I have updated it 
Kindly Review

**Comment by AryanKhubchandani** [comment]
> * Showcase one more implementation using different radius and one using the property clipBehaviour

Please take a look at this point too. There is a clipBehaviour property for ClipRRect, showcase one more example using this property.

**Comment by ShravanSeth** [comment]
Done

**Pull request merged**
