### PR TITLE
Added Switch widget

### PR DESCRIPTION
**Pull request by shiv2299**

### CODE REVIEW

**Comment by AryanKhubchandani** [comment]
Hey @shiv2299! I request you to attach screenshots of your work for the review. 
Thanks

**Comment by shiv2299** [comment]
Screenshot_2021-10-04-12-27-40-475_com example fludget
Screenshot_2021-10-04-12-27-42-644_com example fludget

**Review by AryanKhubchandani — CHANGES_REQUESTED** [review]
Hey @shiv2299, great work! But a few changes need to be made:
1) backgroundColor in the implementation tab needs to be fixed. It should be of the same color as the rest of the application.
2) It would be better if you describe the widget as well in a few lines. Add the description above the code you have included.
3) Add a disabled switch implementation as well.
Let me know if you have any doubts

**Comment by shiv2299** [comment]
Hi @AryanKhubchandani, I have made the requested changes. Attaching a video for a demonstration.
fludget-switch-demo

**Review by AryanKhubchandani — APPROVED** [review]
Looks good to me, thanks for your contribution @shiv2299!

**Pull request merged**
