### PR TITLE
Remove Cupertino Widget & BottomBar, Rename Title "Window Catalog"

### LINKED ISSUE #317: Remove Cupertino Widget Section
Cupertino Widget section needs to be removed. As only one tab will be left at the bottom, remove the BottomTabBar as well and make the changes accordingly. Change the Title of the App bar from 'Material Widget Catalog' to 'Widget Catalog'.

### PR DESCRIPTION
**Pull request by deltarfd**
I've removed the `Cupertino` widget, removed the `bottomBar`, and changed the `AppBar` title to **"Widget Controller"**. You can do a review of the PR. Thank You

https://github.com/ACM-VIT/fludget/issues/317

### CODE REVIEW

**Review by AryanKhubchandani — CHANGES_REQUESTED** [review]
Please make the changes proposed in the issue. Also what is 'Widget Controller"?

**Review by deltarfd — COMMENTED** [review]
Hello, I have changed it according to the issue given. The title has been changed to "Widget Catalog". I just made a typo when commenting on PR. Also I fixed the class name "WidgetCategoy" to "WidgetCategory"

**Comment by AryanKhubchandani** [comment]
Please resolve the conflicts

**Review by deltarfd — COMMENTED** [review]
I have resolved the conflict, You can review it again. Thank you

**Review by AryanKhubchandani — COMMENTED** [review]
Gg @deltarfd

**Pull request merged**
