### PR TITLE
Implemented DatePickerDialog Widget in the Widget Catalog

### PR DESCRIPTION
**Pull request by sachin161kr**
https://user-images.githubusercontent.com/70368661/137623359-a92cecaa-219a-40ae-a86a-f6f321093659.mp4

Hey!!.. I have implemented the DatePicker widget . Kindly review.

### CODE REVIEW

**Comment by AryanKhubchandani** [comment]
> Hey!! I am facing some issue in fetching upstream.
> 
> after clicking on fetch upstream I get this message - Open a pull request to fetch upstream and review changes or resolve conflicts. Have I done something wrong?

Can you share a screnshot of the same?

**Comment by sachin161kr** [comment]
Sure.. I am attaching the screenshot.
Screenshot (357)

**Comment by sachin161kr** [comment]
Let me close this pull request for a while. I need some time to resolve this one.

**Comment by AryanKhubchandani** [comment]
Dont close it, lets try to fix the issue.

**Pull request closed without merging**
