### PR TITLE
Add search feature

### PR DESCRIPTION
**Pull request by RandyKdev**
This PR addresses issue #1, adds the search feature

A models folder was created and this will hold the details of a widget at a high level.

Here is how it looks and functions, shown by the video below

https://user-images.githubusercontent.com/42704349/135725948-36aee4fa-26f5-49c7-b44a-deffcc5a91fc.mp4

Hacktoberfest Contribution

### CODE REVIEW

**Review by AryanKhubchandani — CHANGES_REQUESTED** [review]
Great work @RandyKdev! I would like to bring it to your notice that there has been some changes in the  homepage from another PR according to which some changes need to be made here. Please look into that. 
Thankyou for your cooperation.

**Comment by RandyKdev** [comment]
Ok, @AryanKhubchandani. I have updated the code.

**Comment by RandyKdev** [comment]
All updates done.

**Review by DarthBenro008 — APPROVED** [review]
Thank you for this PR! This looks good to me, @AryanKhubchandani please test this once and you are good to merge this

**Comment by AryanKhubchandani** [comment]
> All updates done.

Great work @RandyKdev! Thanks for your contribution!

**Comment by RandyKdev** [comment]
Thanks @AryanKhubchandani  and @DarthBenro008. If there are any other issues, I will be glad to take a look.

**Pull request merged**
