### PR TITLE
added a listtile widget

### PR DESCRIPTION
**Pull request by samyakjain26**

### CODE REVIEW

**Comment by samyakjain26** [comment]
Screenshot_20211005-224336

**Review by AryanKhubchandani — CHANGES_REQUESTED** [review]
Good Work @samyakjain26, all the features have been implemented properly by you.
But you have forgotten to add description for the widget (mentioned in #35)
Please make sure to add a brief description describing the widget.

**Comment by samyakjain26** [comment]
Hello @AryanKhubchandani I have added the description Please check

**Review by AryanKhubchandani — APPROVED** [review]
Everything looks good to me, GG @samyakjain26! Thanks for your contribution!

**Comment by AryanKhubchandani** [comment]
P.S. Make sure to resolve conflicts by syncicing before you push your work.

**Pull request merged**
