### PR TITLE
Add floating action button in widget implementation screen

### PR DESCRIPTION
**Pull request by RandyKdev**
This PR addresses issue #25

The changes made:
Added support for AndroidX
Fix Naming convention widgets from ...WidgetSample to ...Implementation
Added links to existing widgets
Added floating action button in details of widgets

Here is a screenshot showing the floating action button

Screenshot_20211004-181111

Hacktoberfest Contribution

### CODE REVIEW

**Comment by RandyKdev** [comment]
> Thanks @RandyKdev, for opening the pull request! raised_hands One of our team-mates will review the pull request soon. white_check_mark

Ok, thanks.

**Review by AryanKhubchandani — CHANGES_REQUESTED** [review]
Appreciate the changes made! Well done @RandyKdev!
But there are a few changes which need to be addressed before merging:
1) As mentioned in #25, the button is supposed to be in Description tab, not Implementation tab
2) The color of the FloatingActionButton should be orange[900], blue color looks out of place to me. 

Let me know if you have any other doubt.
Thanks

**Comment by RandyKdev** [comment]
Ok, I will make the changes

**Comment by RandyKdev** [comment]
All requested changes have been done.

Here is a screenshot:

Screenshot_20211004-220309

**Review by AryanKhubchandani — APPROVED** [review]
Everything looks good to me, great work @RandyKdev! 
Thankyou for your contribution 👍

**Pull request merged**
