### PR TITLE
Adding Flow Widget (Feature)

### PR DESCRIPTION
**Pull request by babu1998**
### Light Mode Pics

Screenshot 2021-10-30 at 6 56 28 PM

Screenshot 2021-10-30 at 6 57 04 PM

Added under the animation tag

Screenshot 2021-10-30 at 6 57 27 PM

Screenshot 2021-10-30 at 6 57 43 PM

Screenshot 2021-10-30 at 6 57 55 PM

### Dark Mode Pics

Screenshot 2021-10-30 at 6 58 20 PM

Screenshot 2021-10-30 at 6 58 43 PM

Screenshot 2021-10-30 at 6 58 56 PM

### CODE REVIEW

**Comment by babu1998** [comment]
Fixes https://github.com/ACM-VIT/fludget/issues/278

**Review by AryanKhubchandani — COMMENTED** [review]
Please attach a screen recording of the same.

**Comment by babu1998** [comment]
https://user-images.githubusercontent.com/20140511/139554281-4120eaee-cb07-432f-b455-44a4385f04b4.mp4

**Comment by babu1998** [comment]
uploaded the recording

**Comment by babu1998** [comment]
@AryanKhubchandani

**Pull request merged**
