### PR TITLE
Added ListView.Builder()

### PR DESCRIPTION
**Pull request by sj9102001**
Hey, Please review my PR of issue #5, added following 

- Added an itemMap, enabled dynamic fetching of Widgets to ListTile.
- Also, removed two subtitles as there were only in two, please let me know if you have subtitles for all ListTiles.

Thanks.

### CODE REVIEW

**Comment by AryanKhubchandani** [comment]
Hey @sj9102001, can you please attach screenshots for reference here?

**Comment by sj9102001** [comment]
Cool @AryanKhubchandani, Here you go
screenshotapp
!

**Comment by AryanKhubchandani** [comment]
@sj9102001 Great work, but subtitles are needed for some of them to describe the content included in that particular route, so it will be necessary to include them as well. Please make sure you look into that.

**Comment by sj9102001** [comment]
Hey @AryanKhubchandani , I have made the changes accordingly here is the updated screenshot of the app.

image

Please make sure to add your new widgets in the following code snippet like this:

 final itemMap = {
      <"YourTitle" : {TheWidget : "Your Subtitle"}>
    };

**Review by AryanKhubchandani — APPROVED** [review]
Great work @sj9102001! Thanks for you contribution.

**Comment by sj9102001** [comment]
Thanks @AryanKhubchandani , looking forward to contribute more!

**Comment by AryanKhubchandani** [comment]
> Thanks @AryanKhubchandani , looking forward to contribute more!

New issues will be opened soon, keep an eye out for them :p

**Pull request merged**
