### PR TITLE
Added hero animation widget

### PR DESCRIPTION
**Pull request by PruthviSooni**

### CODE REVIEW

**Comment by PruthviSooni** [comment]
added hero animation widget
added sample screen to show hero animation widget

**Comment by PruthviSooni** [comment]
https://user-images.githubusercontent.com/19818661/135895074-ecf188ce-f45f-4c54-8a7c-1ad4817590dc.mp4

**Review by AryanKhubchandani — CHANGES_REQUESTED** [review]
Good job @PruthviSooni, but make sure the issue is raised before opening a PR. I have raised an issue #53 for the same. One change is required here:
Make sure you include a brief description explaining the widget. 
Also make sure you sync before adding the description.
Let me know if you have any doubts. 
Thanks

**Comment by PruthviSooni** [comment]
@AryanKhubchandani  
please check it out I added description for hero widget

**Review by AryanKhubchandani — APPROVED** [review]
Looks good to me, great work @PruthviSooni! There was one more change due because of the implementation of a new feature, but fixed that myself. Thanks for you contribution!

**Pull request merged**
