### PR TITLE
added expanded widget in widgets catalog

### PR DESCRIPTION
**Pull request by purushottam212**
Expanded Widget added in widgets catalog
expanded widget1
expanded_widget2

### CODE REVIEW

**Review by AryanKhubchandani — CHANGES_REQUESTED** [review]
Great work @purushottam212! But the description is missing. You need to add a brief description about the expanded widget in the description tab. Also fix the spelling of 'Description' in the class `ExpandedWidgetDescription`
Let me know if you have any doubts.

**Comment by purushottam212** [comment]
Thank you , I will add detail information about  expanded widget and correcting the spelling as well .
one thing I wanted to know should I add floating action button on Description   page to navigate to the official docs

**Comment by AryanKhubchandani** [comment]
> Thank you , I will add detail information about expanded widget and correcting the spelling as well . one thing I wanted to know should I add floating action button on Description page to navigate to the official docs

You don't need to add the button as of now, someone else is already working to add that feature and it might create conflicts within the repository if you add it as well.

**Comment by purushottam212** [comment]
ok thank you for clarification

**Comment by purushottam212** [comment]
hey , added description for expanded widget 
expanded_description
please check it and let me know if any changes are required..

**Review by AryanKhubchandani — APPROVED** [review]
Looks good to me, GG @purushottam212!

**Pull request merged**
