### PR TITLE
BottomNavBar added

### PR DESCRIPTION
**Pull request by ShravanSeth**

### CODE REVIEW

**Comment by ShravanSeth** [comment]
[2021-10-17 19-07-10.zip](https://github.com/ACM-VIT/fludget/files/7359974/2021-10-17.19-07-10.zip)

**Comment by ShravanSeth** [comment]
Okay I will do the same

**Comment by AryanKhubchandani** [comment]
Please attach screen recording of the changes you made

**Comment by ShravanSeth** [comment]
Okay

**Comment by ShravanSeth** [comment]
Please review

**Comment by ShravanSeth** [comment]
Thank You

**Pull request merged**
